version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 6329
      MYSQL_DATABASE: fornecedores_db
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db